spring:
  application:
    name: password
    artifactId: password
    group-id: password
    version: 0.0.1-SNAPSHOT
    description: Password management application
    url: http://localhost:8080
    icon-url: http://localhost:8080/favicon.ico
    license-url: http://localhost:8080/license.html

  datasource:
    url: jdbc:postgresql://localhost:5432/pmdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always
    platform: postgres
    schema-generate: CREATE_DROP
    data-generate: CREATE_DROP
    schema-update: true
    data-update: true
    continue-on-error: true
    continue-on-null-pointer-exception: true
    continue-on-data-access-error: true
    continue-on-exception: true
    continue-on-error-key: true
    continue-on-null-pointer-exception-key: true
    continue-on-data-access-error-key: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      format_sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
